# Simple MiR Fleet Configuration
# Copy to config/my_fleet.yaml and update with your details

common:
  connector_type: MiR100
  connector_version: "0.2.2"
  location_tz: America/Los_Angeles
  
  mir_api_version: v2.0
  mir_firmware_version: v3
  mir_use_ssl: false
  
  enable_mission_tracking: false
  enable_temporary_mission_group: true
  
  env_vars:
    INORBIT_API_KEY: "${INORBIT_API_KEY}"

my-robot:
  inorbit_robot_key: your-robot-key-here
  mir_host_address: 192.168.1.100
  mir_host_port: 80
  mir_username: "${MIR_USERNAME}"
  mir_password: "${MIR_PASSWORD}"
