exclude: '.git/'
exclude: '.yaml'
default_stages: [commit]
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-ast
      - id: debug-statements
      - id: check-builtin-literals
      - id: check-docstring-first
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    - id: black
      args: [
        --check,
        --line-length=100,
      ]
  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
    - id: flake8
      additional_dependencies: [
        'flake8-blind-except',
        'flake8-docstrings',
        'flake8-bugbear',
        'flake8-comprehensions',
        'flake8-docstrings',
        'flake8-implicit-str-concat',
        'pydocstyle>=5.0.0',
      ]
      args: [
        --max-line-length=100
      ]