# SPDX-FileCopyrightText: 2025 InOrbit, Inc.
#
# SPDX-License-Identifier: MIT

# This file defines example actions that trigger specific behavior on the robot.
# It is recommended to apply them on a hardware tag scope.

# For InOrbit Actions documentation, see:
# https://developer.inorbit.ai/docs#configuring-action-definitions

# Run a cleaning task on the current map
apiVersion: v0.1
kind: ActionDefinition
metadata:
    id: clean-zone-1
    scope: tag/<account_id>/<tag_id>
spec:
  label: Clean zone 1
  group: Gausium actions
  type: RunScript
  arguments:
    - name: filename
      type: string
      value: start_cleaning_task
    - name: path_name
      type: string
      value: cleaning_zone_1
  confirmation:
    required: true
  lock: false
  description: Runs a cleaning task on the current map
  group: Cleaning tasks
  # Example condition to allow the action to be executed only on specific robots
  condition:
    rules:
    - collections:
      - <tag_id of the gausium hardware>
      - <tag_id of the map to clean>
---
# Run a cleaning task on a path selected by the user
apiVersion: v0.1
kind: ActionDefinition
metadata:
    id: clean-zone-custom
    scope: tag/<account_id>/<tag_id>
spec:
  label: Clean zone custom
  group: Gausium actions
  type: RunScript
  arguments:
    - name: filename
      type: string
      value: start_cleaning_task
    - name: path_name
      type: string
      input:
        control: select
        values:
          - label: cleaning_zone_1
            value: cleaning_zone_1
          - label: cleaning_zone_2
            value: cleaning_zone_2
  confirmation:
    required: true
  lock: false
  description: Runs a cleaning task on a path selected by the user
  group: Cleaning tasks
---
# Run a cleaning task controlling all available arguments
apiVersion: v0.1
kind: ActionDefinition
metadata:
    id: clean-zone-2
    scope: tag/<account_id>/<tag_id>
spec:
  label: Clean zone 2
  group: Gausium actions
  type: RunScript
  arguments:
    - name: filename
      type: string
      value: start_cleaning_task
    - name: path_name
      type: string
      value: path_name
    # Defaults to the current map
    - name: map_name
      type: string
      value: map_name
    # Defaults to False
    - name: loop
      type: boolean
      value: true
    # Defaults to 0
    - name: loop_count
      type: number
      value: 1
    # Defaults to "InOrbit cleaning task action"
    - name: task_name
      type: string
      value: task_name
  confirmation:
    required: true
  lock: false
  description: Runs a very specific cleaning task
  group: Cleaning tasks
---
# Pause the current cleaning task
apiVersion: v0.1
kind: ActionDefinition
metadata:
    id: pause-cleaning
    scope: tag/<account_id>/<tag_id>
spec:
  label: Pause Cleaning Task
  group: Cleaning tasks
  type: RunScript
  arguments:
    - name: filename
      type: string
      value: pause_cleaning_task
  confirmation:
    required: true
  lock: false
  description: Pauses a currently running cleaning task
---
# Resume a paused cleaning task
apiVersion: v0.1
kind: ActionDefinition
metadata:
    id: resume-cleaning
    scope: tag/<account_id>/<tag_id>
spec:
  label: Resume Cleaning Task
  group: Cleaning tasks
  type: RunScript
  arguments:
    - name: filename
      type: string
      value: resume_cleaning_task
  confirmation:
    required: true
  lock: false
  description: Resumes a previously paused cleaning task
---
# Cancel the current cleaning task
apiVersion: v0.1
kind: ActionDefinition
metadata:
    id: cancel-cleaning
    scope: tag/<account_id>/<tag_id>
spec:
  label: Cancel Cleaning Task
  group: Cleaning tasks
  type: RunScript
  arguments:
    - name: filename
      type: string
      value: cancel_cleaning_task
  confirmation:
    required: true
  lock: false
  description: Cancels a currently running cleaning task
---

### Navigation tasks

# Send the robot to a named waypoint
# This could be a dock, in which case the robot will automatically dock
apiVersion: v0.1
kind: ActionDefinition
metadata:
    id: dock
    scope: tag/<account_id>/<tag_id>
spec:
  label: Dock
  group: Navigation tasks
  type: RunScript
  arguments:
    - name: filename
      type: string
      value: send_to_named_waypoint
    - name: position_name
      type: string
      value: dock_position_name
  confirmation:
    required: true
  lock: false
  description: Sends the robot to the charging dock
---
# Send the robot to a named waypoint controlling all available arguments
apiVersion: v0.1
kind: ActionDefinition
metadata:
    id: send-to-named-waypoint
    scope: tag/<account_id>/<tag_id>
spec:
  label: Send to named waypoint
  group: Navigation tasks
  type: RunScript
  arguments:
    - name: filename
      type: string
      value: send_to_named_waypoint
    - name: position_name
      type: string
      value: position_name
    - name: map_name
      type: string
      value: map_name
  confirmation:
    required: true
  lock: false
  description: Sends the robot to a named waypoint
---
# Pause the current navigation task
apiVersion: v0.1
kind: ActionDefinition
metadata:
    id: pause-navigation
    scope: tag/<account_id>/<tag_id>
spec:
  label: Pause Navigation Task
  group: Navigation tasks
  type: RunScript
  arguments:
    - name: filename
      type: string
      value: pause_navigation_task
  confirmation:
    required: true
  lock: false
  description: Pauses a currently running navigation task
---
# Resume a paused navigation task
apiVersion: v0.1
kind: ActionDefinition
metadata:
    id: resume-navigation
    scope: tag/<account_id>/<tag_id>
spec:
  label: Resume Navigation Task
  group: Navigation tasks
  type: RunScript
  arguments:
    - name: filename
      type: string
      value: resume_navigation_task
  confirmation:
    required: true
  lock: false
  description: Resumes a previously paused navigation task
---
# Cancel the current navigation task
apiVersion: v0.1
kind: ActionDefinition
metadata:
    id: cancel-navigation
    scope: tag/<account_id>/<tag_id>
spec:
  label: Cancel Navigation Task
  group: Navigation tasks
  type: RunScript
  arguments:
    - name: filename
      type: string
      value: cancel_navigation_task
  confirmation:
    required: true
  lock: false
  description: Cancels a currently running navigation task
