# Mission Tracking example for robots connected via the MiR <> InOrbit Connector.
# It is recommended to fill the `scope` field with a tag that groups all robots using the connector (e.g. `tag/<ACCOUNT_ID>/<TAG_ID>`).

kind: MissionTracking
apiVersion: v0.1
metadata: 
  # REQUIRED, see note at the beginning of the file.
  scope: <CONFIG_SCOPE>
  id: all
spec:
  processingType:
  - api
  attributes:
    mission_tracking:
    - type: missionApi
  stateDefinitions:
    Executing:
      defaultStatus: OK
