# Data Source example for robots connected via the OTTO <> InOrbit Connector.
# It is recommended to fill the `scope` field with a tag that groups all robots using the connector (e.g. `tag/<ACCOUNT_ID>/<TAG_ID>`).

# The Connector publishes mission status updates on the `mission_status` key.
# This data can be used to display the current robot mode such as missioning, idle, charging, error, etc.
kind: DataSourceDefinition
metadata:
  # REQUIRED, see note at the beginning of the file.
  scope: <CONFIG_SCOPE>
  id: mission_status
apiVersion: v0.1
spec:
  label: Mission Status
  timeline: {}
  source:
    keyValue:
      key: mission_status
