my-example-robot:
  # The timezone of the robot location as a pytz timezone (https://pythonhosted.org/pytz/#helpers)
  location_tz: America/Los_Angeles
  # Connector log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  log_level: INFO
  # The type of connector
  connector_type: V40

  # This is where you define custom fields specific to your robot's connector
  connector_config:
    # Base URL of the API
    base_url: http://ip_and_port
