name: Gausium Connector Workflow

on:
  push:
    branches:
      - main
    paths:
      - gausium_connector/**
  pull_request:
    branches:
      - main
    paths:
      - gausium_connector/**

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Lint with flake8
        uses: py-actions/flake8@v2
        with:
          path: gausium_connector
          max-line-length: 100
      - name: Check with black
        uses: psf/black@stable
        with:
          version: "~= 23.0"
          src: gausium_connector
          options: "--diff --check --line-length=100"

  reuse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v1
        with:
          args: --root gausium_connector lint

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          cd gausium_connector
          python -m pip install --upgrade pip
          python -m pip install -e .["test"]
      - name: Test with pytest
        run: |
          cd gausium_connector
          pytest

  publish-docker:
    if: ${{ contains(github.event.head_commit.message, 'Bump version') }}
    needs: [test, lint]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    environment: release
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set version environment variable
        run: |
          CONNECTOR_VERSION=$(grep -oP '(?<=version = )[^\s]*' gausium_connector/setup.cfg)
          echo "CONNECTOR_VERSION=$CONNECTOR_VERSION" >> $GITHUB_ENV
          echo "CONNECTOR_VERSION is '$CONNECTOR_VERSION'"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Google Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: us-central1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GAR_JSON_KEY }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:gausium_connector"
          file: ./docker/Dockerfile
          push: true
          tags: us-central1-docker.pkg.dev/inorbit-integrations/connectors/gausium_connector:${{ env.CONNECTOR_VERSION }}
