name: Test and Lint

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Lint with flake8
      uses: py-actions/flake8@v2
      with:
        options: "--count --verbose --show-source --statistics"
    - name: Check with black
      uses: psf/black@stable
      with:
        options: "--diff --check"
