name: Test and Lint

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install lint_requirements.txt
    - name: Lint with flake8
      run: |
        flake8 otto_connector --count --verbose --show-source --statistics
    - name: Check with black
      run: |
        black --diff --check otto_connector
